name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # This will run daily at 12:00 PM UTC

jobs:
  commit_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make a commit
      run: |
        echo "Daily commit by 21f3001166@ds.study.iitm.ac.in" >> daily-commit.txt
        git config --global user.email "21f3001166@ds.study.iitm.ac.in"
        git config --global user.name "GitHub Actions"
        git add daily-commit.txt
        git commit -m "Daily commit by 21f3001166@ds.study.iitm.ac.in"
        git push
